# Generated by Django 6.0.5 on 2026-06-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0002_progress_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
